#! /usr/bin/env bash
# Wrapper script to generate table of contents on Markdown files.
# Markdown files must have the `<!-- toc -->` tag in them in order to receive
# a TOC.
#
# This is intended to be called by a pre-commit hook to reduce overhead.
#
# Generated with https://github.com/jonschlinkert/markdown-toc

set -eu -o pipefail

# Get the directory of this file inside pre-commit cache
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MDTOC_BIN="${DIR}/../../node_modules/.bin/markdown-toc"

for filename in "$@"; do
  # Using backticks in this appended comment seems to make the script
  # indicated run after a 3/5 update to markdown-toc 1.2.0;
  # stick with quotes for now.
  regen=$'\n\n<!-- Regenerate with "pre-commit run -a markdown-toc" -->'

  node "${MDTOC_BIN}" --bullets='*' --append="${regen}" -i "${filename}"
  # yarn run --silent markdown-toc --bullets='*' --append="${regen}" -i "${filename}"
done
